spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    serialization:
      write_dates_as_timestamps: false
  datasource:
    username: xpinjection
    password: myPassword
    connectionTimeout: 60000
    maximumPoolSize: 10
    poolName: xpinjectionPostgresPool
    url: jdbc:postgresql://localhost:5432/xpinjection

  liquibase:
    url: jdbc:postgresql://localhost:5432/xpinjection
    user: xpinjection
    password: myPassword

app:
  conference:
    maxAuthorTasksCount: 3
    timeBeforeConference: 1M

